/**
 * Shared PDF helpers for Bartendaz Pro statements.
 * Draws the logo image, header, and footer on each page.
 */

import type { jsPDF } from "jspdf";
import { Capacitor } from "@capacitor/core";

const BRAND_ORANGE = [232, 146, 42] as const;
const PAGE_H = 297;
export const LM = 15;   // left margin
export const RM = 195;  // right margin

/** Fetch logo.png and return a base64 data URL for jsPDF */
async function getLogoDataUrl(): Promise<string | null> {
  try {
    // On native Android the WebView serves assets from the Capacitor URL scheme,
    // not from plain "/". Build the correct URL so the fetch doesn't hang/crash.
    const logoUrl = Capacitor.isNativePlatform()
      ? Capacitor.convertFileSrc("public/logo.png")   // maps to capacitor://localhost/logo.png
      : "/logo.png";

    const res = await fetch(logoUrl);
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror  = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;  // logo is optional — PDF still builds without it
  }
}

/**
 * Draw the page header: logo + business name + document title + divider.
 * Returns the Y position after the header, ready for content.
 */
export async function drawHeader(
  doc: jsPDF,
  businessName: string,
  docTitle: string,
  period: string,
  generated: string
): Promise<number> {
  const logoSize = 18;
  const logoX = LM;
  const logoY = 10;

  // Try to embed the logo PNG
  const logoDataUrl = await getLogoDataUrl();
  if (logoDataUrl && logoDataUrl.startsWith("data:image/png")) {
    try {
      doc.addImage(logoDataUrl, "PNG", logoX, logoY, logoSize, logoSize);
    } catch { /* logo failed — skip it, PDF still works */ }
  }

  const textX = logoX + logoSize + 4;

  // Business name — large and bold
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(businessName, textX, logoY + 6);

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text("Powered by Bartendaz Pro", textX, logoY + 11);

  // Document title — right aligned, orange
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...BRAND_ORANGE);
  doc.text(docTitle, RM, logoY + 6, { align: "right" });

  // Period + generated — right aligned, grey
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text("Period: " + period, RM, logoY + 11, { align: "right" });
  doc.text("Generated: " + generated, RM, logoY + 15, { align: "right" });

  // Divider line
  const y = logoY + logoSize + 4;
  doc.setDrawColor(...BRAND_ORANGE);
  doc.setLineWidth(0.5);
  doc.line(LM, y, RM, y);

  // Reset
  doc.setTextColor(0, 0, 0);
  doc.setLineWidth(0.2);

  return y + 5;
}

/** Draw the footer on the current page */
export function drawFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const footerY = PAGE_H - 8;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(LM, footerY - 3, RM, footerY - 3);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(6.5);
  doc.setTextColor(130, 130, 130);
  doc.text("Official document generated by Bartendaz Pro", LM, footerY);

  doc.setFont("helvetica", "normal");
  doc.text("Page " + pageNum + " of " + totalPages, RM, footerY, { align: "right" });

  doc.setTextColor(0, 0, 0);
  doc.setLineWidth(0.2);
}

/** Stamp footers on every page once the document is fully built */
export function addFootersToAllPages(doc: jsPDF) {
  const total = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    drawFooter(doc, i, total);
  }
}

/** Bottom Y limit before footer — leave room for the footer */
export const CONTENT_BOTTOM = PAGE_H - 15;
