/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootCapacitorRouteImport } from './routes/__root.capacitor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppStockCheckRouteImport } from './routes/_app/stock-check'
import { Route as AppManagerRouteImport } from './routes/_app/manager'
import { Route as AppMachinesRouteImport } from './routes/_app/machines'
import { Route as AppFactoryResetRouteImport } from './routes/_app/factory-reset'
import { Route as AppCreditRouteImport } from './routes/_app/credit'

const _rootCapacitorRoute = _rootCapacitorRouteImport.update({
  id: '/__root/capacitor',
  path: '/capacitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockCheckRoute = AppStockCheckRouteImport.update({
  id: '/stock-check',
  path: '/stock-check',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesRoute = AppMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AppRoute,
} as any)
const AppFactoryResetRoute = AppFactoryResetRouteImport.update({
  id: '/factory-reset',
  path: '/factory-reset',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditRoute = AppCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/capacitor': typeof _rootCapacitorRoute
  '/credit': typeof AppCreditRoute
  '/factory-reset': typeof AppFactoryResetRoute
  '/machines': typeof AppMachinesRoute
  '/manager': typeof AppManagerRoute
  '/stock-check': typeof AppStockCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/capacitor': typeof _rootCapacitorRoute
  '/credit': typeof AppCreditRoute
  '/factory-reset': typeof AppFactoryResetRoute
  '/machines': typeof AppMachinesRoute
  '/manager': typeof AppManagerRoute
  '/stock-check': typeof AppStockCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/__root/capacitor': typeof _rootCapacitorRoute
  '/_app/credit': typeof AppCreditRoute
  '/_app/factory-reset': typeof AppFactoryResetRoute
  '/_app/machines': typeof AppMachinesRoute
  '/_app/manager': typeof AppManagerRoute
  '/_app/stock-check': typeof AppStockCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/capacitor'
    | '/credit'
    | '/factory-reset'
    | '/machines'
    | '/manager'
    | '/stock-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/capacitor'
    | '/credit'
    | '/factory-reset'
    | '/machines'
    | '/manager'
    | '/stock-check'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/__root/capacitor'
    | '/_app/credit'
    | '/_app/factory-reset'
    | '/_app/machines'
    | '/_app/manager'
    | '/_app/stock-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  _rootCapacitorRoute: typeof _rootCapacitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/capacitor': {
      id: '/__root/capacitor'
      path: '/capacitor'
      fullPath: '/capacitor'
      preLoaderRoute: typeof _rootCapacitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stock-check': {
      id: '/_app/stock-check'
      path: '/stock-check'
      fullPath: '/stock-check'
      preLoaderRoute: typeof AppStockCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines': {
      id: '/_app/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AppMachinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/factory-reset': {
      id: '/_app/factory-reset'
      path: '/factory-reset'
      fullPath: '/factory-reset'
      preLoaderRoute: typeof AppFactoryResetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit': {
      id: '/_app/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof AppCreditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCreditRoute: typeof AppCreditRoute
  AppFactoryResetRoute: typeof AppFactoryResetRoute
  AppMachinesRoute: typeof AppMachinesRoute
  AppManagerRoute: typeof AppManagerRoute
  AppStockCheckRoute: typeof AppStockCheckRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreditRoute: AppCreditRoute,
  AppFactoryResetRoute: AppFactoryResetRoute,
  AppMachinesRoute: AppMachinesRoute,
  AppManagerRoute: AppManagerRoute,
  AppStockCheckRoute: AppStockCheckRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  _rootCapacitorRoute: _rootCapacitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
